training: !!bool "true"
device: "cuda"
unprocessed_data: '../data/raw/ESC-50-master/audio/*.wav'
---
data:
    out_path: '../data/processed/ESC_spec/specs'
    sr: 44100
    nfft: 1104 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 80 #Number of mel energies
    # tisv_frame: 180 #Max number of time steps in input after preprocess
    seg_len: 20 # segment length in terms of frame number
    seg_shift: 20 # segment shift interms of frame number
    flooring_dB: -40 # minimum dB